# -*- coding: utf-8 -*-
"""A minúsculas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NnfTAZmeJ53Y7MhRYzsMjlcJQQbyGDyP
"""

def aMinusculas(cadena):
  return cadena.lower()
cadena = input("Ingrese una palabra:")
print ("La nueva palabra es:", aMinusculas(cadena))