# -*- coding: utf-8 -*-
"""Buenas cadenas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Af4Y7ym12uGHyRlQJdUuMOw_mDoo76df
"""

def BuenasCadenas(s):
    caracteres = []
    for letra in s:
        if caracteres and letra.swapcase() == caracteres[-1]:
            caracteres.pop()
        else:
            caracteres.append(letra)
    return ''.join(caracteres)
caracteres = input("Ingrese la cadena:")
print("La cadena buena es:", BuenasCadenas(caracteres))