# -*- coding: utf-8 -*-
"""Código Morse

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZqShxqkmnTZUHAEu0CE4ydEsn8wXHZ7
"""

def aMorse(texto):
    codigo = {'A': ".-",     'B': "-...",   'C': "-.-.",   'D': "-..",    'E': ".",
              'F': "..-.",   'G': "--.",    'H': "....",   'I': "..",     'J': ".---",
              'K': "-.-",    'L': ".-..",   'M': "--",     'N': "-.",     'O': "---",
              'P': ".--.",   'Q': "--.-",   'R': ".-.",    'S': "...",    'T': "-",
              'U': "..-",    'V': "...-",   'W': ".--",    'X': "-..-",   'Y': "-.--",
              'Z': "--..",   ' ': "/"}

    morse = ""
    for char in texto.upper():
        if char in codigo:
            morse += codigo[char] + " "
        elif char == ' ':
            morse += "/ "

    return morse.strip()

def aTexto(morse):
    codigo = {".-": 'A',   "-...": 'B',   "-.-.": 'C',   "-..": 'D',
              ".": 'E',    "..-.": 'F',   "--.": 'G',    "....": 'H',
              "..": 'I',   ".---": 'J',   "-.-": 'K',    ".-..": 'L',
              "--": 'M',   "-.": 'N',     "---": 'O',    ".--.": 'P',
              "--.-": 'Q', ".-.": 'R',    "...": 'S',    "-": 'T',
              "..-": 'U',  "...-": 'V',   ".--": 'W',    "-..-": 'X',
              "-.--": 'Y', "--..": 'Z',   "/": ' '}

    texto = ""
    letras_morse = morse.split(" ")
    for letra_morse in letras_morse:
        if letra_morse in codigo:
            texto += codigo[letra_morse]
        elif letra_morse == '/':
            texto += ' '

    return texto

entrada = input("Ingrese texto o código Morse: ")

if entrada[0] in '-.':
    mensaje = aTexto(entrada)
    print("El mensaje secreto es:", mensaje)
else:
    codigo_morse = aMorse(entrada)
    print("El código Morse es:", codigo_morse)