# -*- coding: utf-8 -*-
"""Triángulo Rectángulo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BSpV3ZZjZquQWI2tJVcEvrCfiZiqpKML
"""

from math import sqrt
def Distancia (x1,y1,x2,y2):
  dx = x2 - x1
  dy = y2 - y1
  return sqrt(dx*dx + dy*dy)

def EsRectangulo(x1,y1,x2,y2,x3,y3):
  a = Distancia(x1,y1,x2,y2)
  b = Distancia (x1,y1,x3,y3)
  c = Distancia(x2,y2,x3,y3)
  return((a*a+b*b==c*c)or(a*a+c*c==b*b)or(b*b+c*c==a*a))
print(EsRectangulo(0,0,0,3,4,0))
print(EsRectangulo(0,0,0,3,4,1))