# -*- coding: utf-8 -*-
"""Pillow

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Gt0Nw2dPSHLMZYwrYKoHD4YjMCVOe1E
"""

# Instalamos Pillow
!pip install Pillow

# Importamos las bibliotecas necesarias
from PIL import Image, ImageFilter, ImageEnhance, ImageOps
from google.colab import files

# Función principal
def main():
    # Subimos el archivo
    uploaded = files.upload()

    # Como solo subí una imagen, trabajo con el primer archivo
    ruta_imagen = list(uploaded.keys())[0]

    # Defino la imagen
    imagen = Image.open(ruta_imagen)

    # Roto la imagen
    imagen_rotada = imagen.rotate(135)
    imagen_rotada.save('imagen_rotada.jpg')
    print("La imagen ha sido rotada satisfactoriamente y guardada como: 'imagen_rotada.jpg'")

    # Le aplico un filtro
    imagen_confiltro = ImageOps.invert(imagen.convert("RGB"))
    imagen_confiltro.save('imagen_confiltro.jpg')
    print("La imagen ha sido filtrada satisfactoriamente y guardada como: 'imagen_confiltro.jpg'")

    # Escala de grises
    imagen_gris = imagen.convert('L')
    imagen_gris.save('imagen_gris.jpg')
    print("La imagen ha sido comvertida a gris satisfactoriamente y guardada como: 'imagen_gris.jpg'")

    # Aumentar Brillo
    enhancer = ImageEnhance.Brightness(imagen)
    imagen_masbrillo = enhancer.enhance(2)
    imagen_masbrillo.save('imagen_masbrillo.jpg')
    print("La imagen ha sido aumentada en brillo satisfactoriamente y guardada como: 'imagen_masbrillo.jpg'")

    # Descargar las imágenes procesadas
    files.download('imagen_rotada.jpg')
    files.download('imagen_confiltro.jpg')
    files.download('imagen_gris.jpg')
    files.download('imagen_masbrillo.jpg')

# Ejecutamos la función principal
main()